import 'dart:convert';
import 'package:supabase_flutter/supabase_flutter.dart';

class NutritionIntakeService {
  final SupabaseClient _supabase = Supabase.instance.client;

  Future<void> addEntry({
    required double energyKcal,
    double? carbsG,
    double? proteinG,
    double? fatG,
    double? sugarG,
    String source = 'ai_analysis',
    Map<String, dynamic>? metadata,
  }) async {
    final user = _supabase.auth.currentUser;
    if (user == null) {
      throw Exception('Please sign in to add intake.');
    }

    final now = DateTime.now();
    final y = now.year.toString().padLeft(4, '0');
    final m = now.month.toString().padLeft(2, '0');
    final d = now.day.toString().padLeft(2, '0');
    final bucketDate = '$y-$m-$d';

    final payload = <String, dynamic>{
      'user_id': user.id,
      'bucket_date': bucketDate,
      'energy_kcal': energyKcal,
      if (carbsG != null) 'carbs_g': carbsG,
      if (proteinG != null) 'protein_g': proteinG,
      if (fatG != null) 'fat_g': fatG,
      if (sugarG != null) 'sugar_g': sugarG,
      if (source.isNotEmpty) 'source': source,
      if (metadata != null) 'metadata': jsonEncode(metadata),
    };

    try {
      await _supabase.from('nutrition_intake').insert(payload);
    } on PostgrestException catch (e) {
      final code = e.code ?? '';
      final msg = e.message ?? '';
      if (code == '42P01' ||
          code == 'PGRST205' ||
          msg.toLowerCase().contains('nutrition_intake') &&
              (msg.toLowerCase().contains('does not exist') || msg.toLowerCase().contains('could not find the table'))) {
        throw Exception(
          'Table nutrition_intake not found. Create it with:\n\n'
          'create table if not exists public.nutrition_intake (\n'
          '  id bigint generated by default as identity primary key,\n'
          '  user_id uuid not null references auth.users(id) on delete cascade,\n'
          '  bucket_date date not null,\n'
          '  energy_kcal double precision not null default 0,\n'
          '  carbs_g double precision,\n'
          '  protein_g double precision,\n'
          '  fat_g double precision,\n'
          '  sugar_g double precision,\n'
          "  source text default 'manual',\n"
          '  metadata jsonb,\n'
          '  created_at timestamptz not null default now()\n'
          ');\n\n'
          'create index if not exists nutrition_intake_user_date on public.nutrition_intake(user_id, bucket_date);\n'
          'alter table public.nutrition_intake enable row level security;\n'
          'create policy "Select own" on public.nutrition_intake for select using (auth.uid() = user_id);\n'
          'create policy "Insert own" on public.nutrition_intake for insert with check (auth.uid() = user_id);\n',
        );
      }
      rethrow;
    }
  }

  Future<Map<String, double>> getTodayTotals() async {
    final user = _supabase.auth.currentUser;
    if (user == null) return {
      'energy_kcal': 0.0,
      'carbs_g': 0.0,
      'protein_g': 0.0,
      'fat_g': 0.0,
      'sugar_g': 0.0,
    };

    final now = DateTime.now();
    final y = now.year.toString().padLeft(4, '0');
    final m = now.month.toString().padLeft(2, '0');
    final d = now.day.toString().padLeft(2, '0');
    final bucketDate = '$y-$m-$d';

    try {
      final resp = await _supabase
          .from('nutrition_intake')
          .select('energy_kcal, carbs_g, protein_g, fat_g, sugar_g')
          .eq('user_id', user.id)
          .eq('bucket_date', bucketDate);

      double sum(String key) {
        if (resp is! List) return 0.0;
        double total = 0.0;
        for (final row in resp) {
          final v = row[key];
          if (v is num) total += v.toDouble();
          else if (v != null) {
            final parsed = double.tryParse(v.toString());
            if (parsed != null) total += parsed;
          }
        }
        return total;
      }

      return {
        'energy_kcal': sum('energy_kcal'),
        'carbs_g': sum('carbs_g'),
        'protein_g': sum('protein_g'),
        'fat_g': sum('fat_g'),
        'sugar_g': sum('sugar_g'),
      };
    } catch (_) {
      return {
        'energy_kcal': 0.0,
        'carbs_g': 0.0,
        'protein_g': 0.0,
        'fat_g': 0.0,
        'sugar_g': 0.0,
      };
    }
  }
}
