import 'package:supabase_flutter/supabase_flutter.dart';

class RelaxService {
  final SupabaseClient _supabase = Supabase.instance.client;

  Future<void> logSession({
    required int minutes,
    String? pattern,
    String? mood,
    DateTime? startedAt,
  }) async {
    final user = _supabase.auth.currentUser;
    if (user == null) throw Exception('Please sign in to log relaxation.');

    final payload = <String, dynamic>{
      'user_id': user.id,
      'minutes': minutes,
      if (pattern != null) 'pattern': pattern,
      if (mood != null) 'mood': mood,
      if (startedAt != null) 'started_at': startedAt.toIso8601String(),
    };

    try {
      await _supabase.from('relax_sessions').insert(payload);
    } on PostgrestException catch (e) {
      final code = e.code ?? '';
      final msg = e.message ?? '';
      if (code == '42P01' ||
          code == 'PGRST205' ||
          msg.toLowerCase().contains('relax_sessions') &&
              (msg.toLowerCase().contains('does not exist') || msg.toLowerCase().contains('could not find the table'))) {
        throw Exception(
          'Table relax_sessions not found. Create it with:\n\n'
          'create table if not exists public.relax_sessions (\n'
          '  id bigint generated by default as identity primary key,\n'
          '  user_id uuid not null references auth.users(id) on delete cascade,\n'
          '  started_at timestamptz not null default now(),\n'
          '  minutes integer not null check (minutes >= 0),\n'
          '  pattern text,\n'
          '  mood text,\n'
          '  created_at timestamptz not null default now()\n'
          ');\n\n'
          'create index if not exists relax_sessions_user_date on public.relax_sessions(user_id, started_at);\n'
          'alter table public.relax_sessions enable row level security;\n'
          'create policy "Select own" on public.relax_sessions for select using (auth.uid() = user_id);\n'
          'create policy "Insert own" on public.relax_sessions for insert with check (auth.uid() = user_id);\n',
        );
      }
      rethrow;
    }
  }

  Future<int> getTodayMinutes() async {
    final user = _supabase.auth.currentUser;
    if (user == null) return 0;
    final now = DateTime.now();
    final start = DateTime(now.year, now.month, now.day);
    final startIso = start.toIso8601String();
    try {
      final resp = await _supabase
          .from('relax_sessions')
          .select('minutes, started_at')
          .eq('user_id', user.id)
          .gte('started_at', startIso);
      int total = 0;
      if (resp is List) {
        for (final row in resp) {
          final v = row['minutes'];
          if (v is int) total += v;
          else if (v is num) total += v.toInt();
          else if (v != null) total += int.tryParse(v.toString()) ?? 0;
        }
      }
      return total;
    } catch (_) {
      return 0;
    }
  }

  Future<int> getLast7DaysMinutes() async {
    final user = _supabase.auth.currentUser;
    if (user == null) return 0;
    final now = DateTime.now();
    final start = DateTime(now.year, now.month, now.day).subtract(const Duration(days: 6));
    final startIso = start.toIso8601String();
    try {
      final resp = await _supabase
          .from('relax_sessions')
          .select('minutes, started_at')
          .eq('user_id', user.id)
          .gte('started_at', startIso);
      int total = 0;
      if (resp is List) {
        for (final row in resp) {
          final v = row['minutes'];
          if (v is int) total += v;
          else if (v is num) total += v.toInt();
          else if (v != null) total += int.tryParse(v.toString()) ?? 0;
        }
      }
      return total;
    } catch (_) {
      return 0;
    }
  }
}

